-- swapson.nvim plugin bootstrap
--
-- lazy.nvim recognizes swapson.nvim as a plugin via this file. The `opts = {...}`
-- shorthand is now a fully supported, safe configuration method:
-- setup() is called automatically by lazy.nvim with your opts table, and the
-- built-in mason-ready guard ensures patching only proceeds once mason.nvim has
-- completed its own setup (require("mason").has_setup == true). If mason is not
-- ready yet, patching is deferred via vim.schedule and retried once.
--
-- The explicit config = function() ... end form continues to work identically.
-- See README.md for both installation styles.
